workflows:
  ios-free-signing:
    name: iOS Free Developer Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: 15.2
      vars:
        APPLE_ID: Environ(APPLE_ID)
        APPLE_PASSWORD: Environ(APPLE_ID_PASSWORD)
    scripts:
      - name: Build unsigned .ipa
        script: |
          xcodebuild -project PrimeraApp.xcodeproj \
          -scheme PrimeraApp \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $CM_BUILD_DIR/PrimeraApp.xcarchive archive

          xcodebuild -exportArchive \
          -archivePath $CM_BUILD_DIR/PrimeraApp.xcarchive \
          -exportPath $CM_BUILD_DIR/ios \
          -exportOptionsPlist ExportOptions.plist
    artifacts:
      - $CM_BUILD_DIR/PrimeraApp.xcarchive/Products/Applications/PrimeraApp.app
      - $CM_BUILD_DIR/ios/*.ipa
    publishing:
      email:
        recipients:
          - mckdesarrollo@gmail.com
