workflows:
  ios-free-signing:
    name: iOS Free Developer Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: 15.2
      vars:
        APPLE_ID: $APPLE_ID
        APPLE_PASSWORD: $APPLE_PASSWORD  
    scripts:
      - name: Build unsigned .ipa
        script: |
          # Archive the app
          xcodebuild -project PrimeraApp.xcodeproj \
          -scheme Prueba22 \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $CM_BUILD_DIR/Prueba22.xcarchive \
          CODE_SIGN_STYLE=Automatic \
          archive

          # Export .ipa with automatic signing
          xcodebuild -exportArchive \
          -archivePath $CM_BUILD_DIR/Prueba22.xcarchive \
          -exportPath $CM_BUILD_DIR/ios \
          -exportOptionsPlist ExportOptions.plist
    artifacts:
      - $CM_BUILD_DIR/ios/*.ipa
      - $CM_BUILD_DIR/Prueba22.xcarchive/Products/Applications/Prueba22.app
      
