workflows:
  ios-build:
    name: iOS build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: 15.2
    scripts:
      - name: Install dependencies
        script: |
          brew install cocoapods || true
          pod install --repo-update || true
      - name: Build app
        script: |
          xcodebuild -project PrimeraApp.xcodeproj \
          -scheme PrimeraApp \
          -configuration Release \
          -sdk iphoneos \
          -archivePath $CM_BUILD_DIR/PrimeraApp.xcarchive archive
    artifacts:
      - $CM_BUILD_DIR/PrimeraApp.xcarchive
      - $CM_BUILD_DIR/PrimeraApp.xcarchive/dSYMs
    publishing:
      email:
        recipients:
          - tuemail@ejemplo.com
