workflows:
  ios-free-signing:
    name: iOS Free Developer Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: 15.2
      vars:
        APPLE_ID: $APPLE_ID
        APPLE_PASSWORD: $APPLE_PASSWORD  
    scripts:
      - name: Build unsigned .ipa
        script: |
          set -o pipefail
          xcodebuild -project PrimeraApp.xcodeproj \
          -scheme PrimeraApp \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $CM_BUILD_DIR/PrimeraApp.xcarchive \
          archive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $CM_BUILD_DIR/ios/*.ipa
      - $CM_BUILD_DIR/PrimeraApp.xcarchive/Products/Applications/PrimeraApp.app
      
